CREATE TABLE PERSONAL_RECORDS (
    ID VARCHAR PRIMARY KEY NOT NULL,
    ATHLETE_ID VARCHAR NOT NULL,
    ATHLETE_NAME VARCHAR NOT NULL,
    EXERCISE_ID VARCHAR NOT NULL,
    EXERCISE_NAME VARCHAR NOT NULL,
    EXERCISE_UNIT VARCHAR NOT NULL,
    PR_DATE DATE NOT NULL,
    PR_VALUE FLOAT NOT NULL,
);

CREATE TABLE EXERCISES (
    ID VARCHAR PRIMARY KEY NOT NULL,
    NAME VARCHAR NOT NULL,
    UNIT VARCHAR NOT NULL
);
